Support table field row -> deleted on Task Comments
simplygoodsoftware/pyrusapi-csharp pull request #139
Opened 2024-01-11 12:14 UTC by pygladilin

2024-01-11 12:21 UTC, alexeyvashchenko requested changes

2024-01-11 12:21 UTC, alexeyvashchenko commented on Entities/FormFields/FormFieldTable.cs
> +		[JsonProperty("deleted", DefaultValueHandling = DefaultValueHandling.Ignore)]
разве так можно? Это же нарушение обратной совместимости

2024-01-11 12:21 UTC, alexeyvashchenko commented on Entities/FormFields/FormFieldTable.cs
> +		[JsonProperty("deleted", DefaultValueHandling = DefaultValueHandling.Ignore)]
И как-то так получилось, что других изменений, кроме переименования этого поля, вообще нет? этого тоже не понял

2024-01-11 12:57 UTC, pygladilin commented on Entities/FormFields/FormFieldTable.cs
> +		[JsonProperty("deleted", DefaultValueHandling = DefaultValueHandling.Ignore)]
Исправил.
Теперь у нас два поля - Delete и Deleted.

2024-01-15 09:32 UTC, alexLopatin approved these changes

2024-01-15 12:48 UTC, alexeyvashchenko approved these changes

2024-01-15 14:28 UTC, merged