Members public api - 76400118
simplygoodsoftware/pyrusapi-csharp pull request #36
Opened 2021-04-01 15:24 UTC by sedyakin

https://pyrus.com/t#id76400118

2021-04-01 15:41 UTC, SBorzov approved these changes

2021-04-06 15:35 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +        public CreateMemberRequestBuilder(string email)
Здесь пробелы

2021-04-06 15:35 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder WithFirstName(string name)
Тут табы

2021-04-06 15:46 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder WithFirstName(string name)
The idea of Builder pattern is to provide humand readable method call chain to construct a request.
In this case all method have the same signature witch does not have a lot of value.

2021-04-06 15:47 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +        private readonly CreateMemberRequest _request;
This class have single costrcutor with only

2021-04-06 15:49 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder WithEmail(string email)
This class have a single costrcutor with email parameter. Having another method to override constructor parameter will lead to a confusion

2021-04-06 15:49 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder WithDepartmentId(int departmentId)
WorkingAt(int departmentId)

2021-04-06 15:50 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder WithPhone(string phone)
WorkPhone(string phone)

2021-04-06 15:57 UTC, mikheevnickita commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder WithFirstName(string name)
```
RequestBuilder
    .CreateAccount(login: "someone@domain.com")
        .For("John", "Doe")
        .WorkingAt(itDepartmentId)
        .As("CTO")
        .WorkPhone("+1(800) 123 4567")
        .Skype("john.doe")
        .Process(apiClient)
```

2021-04-07 09:57 UTC, alexeyvashchenko requested changes

2021-04-07 09:57 UTC, alexeyvashchenko commented on Requests/Builders/CreateMemberRequestBuilder.cs
> +		public CreateMemberRequestBuilder For(string name, string lastName)
назови параметр firstName

2021-04-07 12:02 UTC, alexeyvashchenko approved these changes

2021-04-12 14:24 UTC, mikheevnickita approved these changes

2021-04-12 14:24 UTC, merged