Al/list crud
simplygoodsoftware/pyrusapi-csharp pull request #75
Opened 2022-03-06 13:38 UTC by alexLopatin

2022-03-09 16:22 UTC, alexeyvashchenko requested changes

2022-03-09 16:22 UTC, alexeyvashchenko commented on Entities/PlainTaskList.cs
> +		public int? ExternalId { get; set; }
меня смущает, что
1) добавилось очень много полей. Мы же только внешнюю версию и ид добавили в АПИ, остальные откуда?

2) есть версия и внешняя версия - зачем две? Точно ли обе нужны?

3) названия полей откуда взялись? согласовывал ли ты их с Никитой?

2022-03-09 16:22 UTC, alexeyvashchenko commented on Entities/PlainTaskList.cs
> +		public int? ExternalId { get; set; }
( то же про следующие запросы)

2022-03-10 08:43 UTC, alexLopatin commented on Entities/PlainTaskList.cs
> +		public int? ExternalId { get; set; }
1. Не только. Добавили цвет списка, ид родителя, версию, администраторов и участников + приватный список или нет
2. Нужно знать актуальную версию в облаке
3. Названия полей не согласовывал

2022-03-11 11:21 UTC, alexeyvashchenko approved these changes

2022-03-11 11:21 UTC, merged