Ap/new fields in update member request
simplygoodsoftware/pyrusapi-csharp pull request #86
Opened 2022-04-27 16:55 UTC by AlexandrPyankov

2022-04-28 17:50 UTC, alexeyvashchenko requested changes

2022-04-28 17:50 UTC, alexeyvashchenko commented on Entities/SessionLifespan.cs
> +		public bool? Disable { get; set; }
для LifespanHours значение null видимо означает " наследуется от организации", так? А Disable разве null может быть?

2022-04-28 18:31 UTC, AlexandrPyankov commented on Entities/SessionLifespan.cs
> +		public bool? Disable { get; set; }
Соглашусь. Для public Api здесь null бессмысленно. А по поводу null в lifespan - не совсем так. Оно может быть null, после того как его дропнули. Но если от организации есть наследование значения, то оно придёт в ответе, потому что оно приходит в ответе на сайте. Это наследование реализовано просто через свойство на бэке.

2022-04-29 10:48 UTC, alexeyvashchenko approved these changes

2022-05-04 07:15 UTC, merged